### ISSUE TITLE
BadImageFormatException when using Contract.Ensures in async method, that returns task without any await

### ISSUE THREAD

**Issue by Dennis-Petrov** [Microsoft/CodeContracts#235]
Hi. This code:

    class Program
    {
        static Task<T> Foo<T>(T source)
            where T : class
        {
            Contract.Ensures(Contract.Result<T>() != null);

            return Task.FromResult(source);
        }

        static void Main(string[] args)
        {
            Foo(new object()).Wait();
        }
    }

leads to `BadImageFormatException`, while this one - not:

        static async Task<T> Foo<T>(T source)
            where T : class
        {
            Contract.Ensures(Contract.Result<T>() != null);

            return await Task.FromResult(source);
        }

The only difference is awaiting the task in the second sample, which is totally unnecessary here.  

It seems to me, that using `Contract.Result<T>()` in `Foo` is logically incorrect here too .We're not *awaiting* a task result, we're just *returning* a task. Though, `BadImageFormatException` shouldn't be thrown, and I need a way to point CC to check task result here.

Is there any workarounds instead of `await`?

**Comment by yaakov-h** [comment]
I believe `Contract.Result<T>()` on a method returning `Task<T>` is only valid on `async` methods, but I'd expect a rewriter error, not a runtime error.

**Comment by SergeyTeplyakov** [comment]
@yaakov-h `Contract.Result<T>()` is valid for both: async and non-async methods.

I've check whether my fix (https://github.com/Microsoft/CodeContracts/pull/159) helps this, but I'm not sure that it will.

BTW, please note, that this code fails on both: VS2015 and VS2013.

**Comment by SergeyTeplyakov** [comment]
BTW, please note, that switching to "async" does not help either: in this case there is no `BadImageFormatException` but resulting code is not valid.

For this code:

```c#
class Program
{
    public static async Task<T> Foo<T>(T source)
    where T : class
    {
        Contract.Ensures(Contract.Result<T>() != null);
        await Task.Yield();
        return source;
        //return Task.FromResult(source);
    }

    static void Main(string[] args)
    {
        Foo("foo").Wait();
    }
}
```

ccrewrite generates following code:

```c#
public static Task<T> Foo<T>(T source) where T : class
{
	Program.<Foo>d__0<T> <Foo>d__;
	<Foo>d__.source = source;
	<Foo>d__.<>t__builder = AsyncTaskMethodBuilder<T>.Create();
	<Foo>d__.<>1__state = -1;
	AsyncTaskMethodBuilder<T> <>t__builder = <Foo>d__.<>t__builder;
	<>t__builder.Start<Program.<Foo>d__0<T>>(ref <Foo>d__);
	Task<T> task = <Foo>d__.<>t__builder.Task;
	Task<T> task2 = task;
	if (__ContractsRuntime.insideContractEvaluation <= 4)
	{
		try
		{
			__ContractsRuntime.insideContractEvaluation++;
			__ContractsRuntime.Ensures(task2.Result != null, null, "Contract.Result<T>() != null");
		}
		finally
		{
			__ContractsRuntime.insideContractEvaluation--;
		}
	}
	return task2;
}
```

I.e. the postcondition is synchronous and not asynchronous!

**Comment by SergeyTeplyakov** [comment]
@Dennis-Petrov I've posted PR with a fix. Will appreciate some feedback:)

**Comment by Dennis-Petrov** [comment]
@SergeyTeplyakov, sorry, I've lost sight of this issue.
This particular case is fixed in [RC](https://github.com/Microsoft/CodeContracts/releases/tag/v1.10.10126.2), but this code still raises `BadImageFormat`:

    class Program
    {
        static void Main(string[] args)
        {
            new Foo().GetBarsAsync<Boo>().Wait();
        }
    }

    abstract class Bar { }
    class Boo : Bar { }

    [ContractClass(typeof(FooContract))]
    interface IFoo
    {
        Task<IEnumerable<TBar>> GetBarsAsync<TBar>()
            where TBar : Bar;
    }

    [ContractClassFor(typeof(IFoo))]
    abstract class FooContract : IFoo
    {
        public Task<IEnumerable<TBar>> GetBarsAsync<TBar>()
            where TBar : Bar
        {
            Contract.Ensures(Contract.Result<IEnumerable<TBar>>() != null);

            throw new NotImplementedException();
        }
    }

    class Foo : IFoo
    {
        public Task<IEnumerable<TBar>> GetBarsAsync<TBar>() where TBar : Bar
        {
            return Task.FromResult(Enumerable.Empty<TBar>());
        }
    }

Was this case fixed already?

Unfortunately, I can't check this myself by building master branch, because something broken there: I've tried to do that, but in spite of successful build in VS2013, re-writer fails on one of my projects - it can't resolve some types, defined in assembly being rewritten, while RC - does not (hence, I've uninstalled it).

**Comment by DzheiZee** [comment]
Using 1.10.20606.1
Still encountering such defect.
Is fix for this defect included into given version (afaik it is the latest released version)
